### ISSUE TITLE
Site crashes when loading

### ISSUE THREAD

**Issue by evilteq** [oatear/cider#90]
Current version crashes when loading the website:
`main.39f13294df587ec6.js:1 TypeError: window.require is not a function
    at t.getIpcRenderer (main.39f13294df587ec6.js:1:1587205)
    at new t (main.39f13294df587ec6.js:1:1586776)
    at t.ɵfac [as factory] (main.39f13294df587ec6.js:1:1591485)
    at m4.hydrate (main.39f13294df587ec6.js:1:54642)
    at m4.get (main.39f13294df587ec6.js:1:53206)
    at PH.get (main.39f13294df587ec6.js:1:72646)
    at q2 (main.39f13294df587ec6.js:1:33695)
    at v1 (main.39f13294df587ec6.js:1:34186)
    at mt (main.39f13294df587ec6.js:1:59111)
    at t.ɵfac [as factory] (main.39f13294df587ec6.js:1:1625160)`

**Comment by hristoiankov** [comment]
Thank you for the report. This has been fixed.
